- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted

- name: restart auditd
  command: /usr/sbin/service auditd restart